### ISSUE TITLE
Tunnel ip layer

### ISSUE THREAD

**Issue by Fabrizzz** [kinnay/LDN#3]
Hi,
I was trying to understand how LDN works and what I understood is that it implements an ad hoc wifi network using custom frames at data link layer. But then, wouldn't it be possible to use something similar to your code to connect two nintendo switch to two different computers (the host switch to a computer using your join.py and vice versa) and then tunnel all the ip level traffic between the two computers in order to play remotely? I since nobody already did it, is there something i am missing? Do you think it would be feasible to completely emulate and manage the ldn data link layer to make it work while gaming?

**Comment by kinnay** [comment]
Yes I'm quite sure that's possible.

I actually tried it once, but in a different way, without emulating LDN at all, by tunneling raw 802.11 frames in monitor mode.

It didn't work at the time. I think the reason was that one of our wifi chips didn't support monitor mode properly (it didn't receive any action frames).

Below is the script that I used. The server just broadcasts any incoming packets to all connected clients in this case.

```python
import struct
import socket
import trio

# MAC address of Nintendo Switch
MACADDR = bytes([0x12, 0x34, 0x56, 0x78, 0x9A, 0xBC])
SERVERADDR = ("95.179.133.193", 21000)
IFNAME = "wlp2s0"

# Receives frames from Switch and sends them to the server
async def recv_loop(socket, client):
	while True:
		data = await socket.recv(65536)
		
		# Skip radiotap header
		length = struct.unpack_from("<H", data, 2)[0]
		data = data[length:]
		
		# Filter frames on mac address
		if data[10:16] == MACADDR:
			await client.send(struct.pack(">I", len(data)) + data)

# Receives frames from the server and sends them to the Switch
async def send_loop(socket, client):
	data = b""
	while True:
		while len(data) < 4:
			data += await client.recv(65536)
		
		length = struct.unpack_from(">I", data)[0]
		data = data[4:]
		while len(data) < length:
			data += await client.recv(65536)
		
		packet = data[:length]
		data = data[length:]
		
		# Add radiotap header
		packet = struct.pack("<BBHI", 0, 0, 8, 0) + packet
		await socket.send(packet)


ETH_P_ALL = 3
async def main():
	sock = trio.socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(ETH_P_ALL))
	await sock.bind((IFNAME, 0))
	
	client = trio.socket.socket(socket.AF_INET, socket.SOCK_STREAM, socket.IPPROTO_TCP)
	await client.connect(SERVERADDR)
	
	async with trio.open_nursery() as nursery:
		nursery.start_soon(recv_loop, sock, client)
		nursery.start_soon(send_loop, sock, client)

trio.run(main)
```

**Comment by Fabrizzz** [comment]
I guess this is the only feasible approach. Since i don't know the game-specific key, i cannot decrypt any data frames except for the Advertisement Frames (I tried to use your join.py for a game of Animal Crossing, but of course i couldn't make it work without the password). 
Looking at this script i was wondering a few things. Is there a reason why you use Mac Address to filter frames to sniff and then send over to the server? Wouldn't it be possible to just use the initial bytes that contains "Magic numbers" to filter nintendo frames, and just redirect all of them? Or are they encrypted too?

**Comment by kinnay** [comment]
Yes there are a few reasons:
* Filtering frames on mac address is easy, whereas using a magic number requires knowledge of the ldn protocol.
* Data frames are encrypted, so the mac address is probably the only way to filter the frames without decrypting them, which would be very complicated.
* When the Switch is part of an ldn network, it does not transmit any other frames, so we get exactly the frames that we want (no more and no less).
